import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/search.css";
import Search from "@/components/layout/search";
import "core-js/actual/object/group-by";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Search/>
        {children}
      </body>
    </html>
  );
}
