import type { Metadata } from "next";
import "@/styles/globals.scss";
import "@/styles/search.scss";
import Search from "@/components/layout/search";
import { AuthProvider } from "@/context/AuthContext";
import Tools from "@/components/layout/tools";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
          <AuthProvider>
            <Tools/>
            <div className="main">{children}</div>
            <Search/>
          </AuthProvider>
      </body>
    </html>
  );
}
